### PR TITLE
Updating a license

### PR DESCRIPTION
**Pull request by kubawerlos**
A license for open source project should not be "proprietary": https://getcomposer.org/doc/04-schema.md#license

### CODE REVIEW

**Comment by slk500** [comment]
You're right. Give me some time to think which licence would fit the most.

**Comment by slk500** [comment]
Please change it to GNU General Public License v3.0 | gpl-3.0

**Comment by slk500** [comment]
hmm I have chosen the licence base on GitHub page https://help.github.com/en/articles/licensing-a-repository so I think it would be enough to just write 'gpl-3.0'.

**Comment by kubawerlos** [comment]
Updated, with license text from https://www.gnu.org/licenses/gpl-3.0.txt

**Pull request merged**
